### ISSUE TITLE
the kernel not works for raspbian 2018-04-18-raspbian-stretch img

### ISSUE THREAD

**Issue by plattowang** [lemariva/RT-Tools-RPi#1]
Hi Guys.
I use the img, dtb, dtbo and module file here to replace the raspbian 2018-04-18-raspbian-stretch kernel files.  I modified the config.txt to set the kenerl and device_tree.But  the OS system cant' boot on raspberry PI 3 B+: black screen and green led blink.
 
So any things is wrong ?

**Comment by lemariva** [comment]
Hi, please for the kernel file under kernel_4_14_52-rt34-v7+ follow the steps describe from here: https://lemariva.com/blog/2018/07/raspberry-pi-preempt-rt-patching-tutorial-for-kernel-4-14-y#transfer-the-kernel
Otherwise, you can compile the kernel yourself with the instructions in that post, but for the transfer and deployment the compiled file should work. I tested it with the raspberry pi b+.
